const GAME_WIDTH = 960;
const GAME_HEIGHT = 540;

const PLAYER_BASE_SPEED = 220;
const PLAYER_BASE_FIRE_DELAY = 450; // ms
const PLAYER_BASE_BULLET_SPEED = 420;
const PLAYER_BASE_DAMAGE = 1;
const PLAYER_BASE_MAX_HP = 5;

const ZOMBIE_BASE_SPEED = 60;
const ZOMBIE_HP = 3;
const ZOMBIE_SPAWN_INTERVAL = 2500; // ms
